---
title: "Deberes Román"
author: "Román Mínguez"
date: "8/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. Montar una función para calcular el test Q asintótico (en vez de calcular primero las mh y los símbolos) con los siguientes argumentos:

- Y = un factor con las categorías
- x = las coordenadas de cada punto
- m = tamaño m-historia
- s = grado de solapamiento
- type = con símbolos ‘p’ o ‘c’
- control:
* generando m-historias con ‘m_surr_no’ se puede controlar el grado de degeneración de las h-historias (ver código)
* Obtener m-historias con ‘m_surr_no2’ con mas o menos permutaciones
 
2. Montar una función para QBoots (Q con Montecarlo). Argumentos:
-  Y = un factor con las categorías
- x = las coordenadas de cada punto
- m = tamaño m-historia
- type = con símbolos ‘p’ o ‘c’
- nsim = número de réplicas
- control: 
- Defecto sin solapamiento OPCIONAL s = grado de solapamiento
 
3. Revisar función DGP
 
 
* Crear la clase spq
 
Definir los siguientes métodos aplicados a la clase spq:
 
* plot – Para obtener el histograma de frecuencias de los símbolos

* summary – debe imprimir una tabla, listanto los símbolos, sus frecuencias observadas, frecuencias esperadas e intervalo de confianza. Con asterisco los símbolos con frecuencia observada fuera del IC

* print – imprime el output natural de estadístico
